project:
  type: website
  output-dir: _site

website:
  title: "Thomas Martin"
  site-url: https://personalWebsite.github.io
  description: "Analytics, modelling, and reproducible research."
  favicon: /favicon.ico

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      #- text: Blog
       # href: posts/index.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/Gippers

  page-footer:
    center: "2025 Â· Built with Quarto"

format:
  html:
    theme: 
      light: flatly
      dark: darkly   # or another dark Bootswatch theme
    toggle: true
    css: styles.css
    toc: true
    link-external-newwindow: true
    smooth-scroll: true
    code-copy: true

execute:
  freeze: auto   # reproducible builds for posts

# Optional: RSS for posts
metadata-files:
  - _meta.yml
